/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Componentes;


import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.sound.sampled.*;
import java.io.IOException;
import java.net.URL;

/**
 *
 * @author BolilloCPU
 */
public class DiscoDraft extends javax.swing.JPanel {

    private Clip clip;
    private ImageIcon imgGif;
    private ImageIcon portada;
    private ImageIcon contraportada;
    
    private Thread hiloCambioImagen;
    private boolean activo = true;
    private boolean mostrarPortada = true;
    

    public DiscoDraft() {
        initComponents();
        imgGif = new ImageIcon(getClass().getResource("src/imagenes/gifDisco.gif")); 
        portada = new ImageIcon(getClass().getResource("src/imagenes/darfpunkPor.jpg")); 
        contraportada = new ImageIcon(getClass().getResource("src/imagenes/contraDraf.png")); 
        
        lblKirby.setIcon(null); // no mostrar gif al inicio
        lblKirby1.setIcon(portada); // mostrar primero la portada
        btnBoton.addMouseListener(new interna());
        
        iniciarCambioImagenes();
    }

    class interna extends MouseAdapter {
        
        public void mouseClicked(MouseEvent e) {
            if (lblKirby.getIcon() == null) {
                detenerCambioImagenes();
                lblKirby1.setVisible(false); // oculta portada/contraportada
                lblKirby.setIcon(imgGif); // muestra gif
                btnBoton.setText("Detener");
            } else {
                lblKirby.setIcon(null); // quita gif
                lblKirby1.setVisible(true); // vuelve a mostrar imágenes
                btnBoton.setText("Escuchar");
                iniciarCambioImagenes(); // reanudar cambio de imágenes
            }
        }
    }

    private void iniciarCambioImagenes() {
        activo = true;
        hiloCambioImagen = new Thread(new CambioImagenRunnable());
        hiloCambioImagen.start();
    }
    
    private void detenerCambioImagenes() {
        activo = false;
        if (hiloCambioImagen != null && hiloCambioImagen.isAlive()) {
            hiloCambioImagen.interrupt();
        }
    }
    
    class CambioImagenRunnable implements Runnable {
        
        public void run() {
            while (activo) {
                try {
                    if (mostrarPortada) {
                        lblKirby1.setIcon(portada);
                    } else {
                        lblKirby1.setIcon(contraportada);
                    }
                    mostrarPortada = !mostrarPortada; // alternar
                    Thread.sleep(3000); // cada x segundos
                } catch (InterruptedException ex) {
                    break; // si interrumpe salir
                }
            }
        }
    }

    private void reproducirSonido() {
        try {
            if (clip != null) {
                if (clip.isRunning()) {
                    clip.stop(); // si está sonando detener
                    return;
                }
            }
            URL sonidoURL = getClass().getResource("/PruebaAudio1.wav");
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(sonidoURL);
            clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }

}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        lblKirby = new javax.swing.JLabel();
        btnBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblKirby1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setBackground(new java.awt.Color(102, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKirby.setBackground(new java.awt.Color(102, 102, 102));
        add(lblKirby, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 521, 409));

        btnBoton.setBackground(new java.awt.Color(51, 51, 51));
        btnBoton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnBoton.setForeground(new java.awt.Color(255, 255, 255));
        btnBoton.setText("Escuchar");
        btnBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotonActionPerformed(evt);
            }
        });
        add(btnBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 193, 73, 33));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Componente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 19, 131, 22));

        lblKirby1.setBackground(new java.awt.Color(102, 102, 102));
        add(lblKirby1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 47, 521, 409));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotonActionPerformed
       reproducirSonido();
    }//GEN-LAST:event_btnBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblKirby;
    private javax.swing.JLabel lblKirby1;
    // End of variables declaration//GEN-END:variables
}
