/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ruidosperdidos;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.sound.sampled.*;
import java.io.IOException;
import java.net.URL;

/**
 *
 * @author BolilloCPU
 */
public class VentanaDraf extends javax.swing.JFrame {

       private Clip clip;
    private ImageIcon imgGif;
    private ImageIcon portada;
    private ImageIcon contraportada;
    
    private Thread hiloCambioImagen;
    private boolean activo = true;
    private boolean mostrarPortada = true;
    
    public VentanaDraf() {
        initComponents();
        imgGif = new ImageIcon(getClass().getResource("/imagenes/gifDisco_1.gif")); 
        portada = new ImageIcon(getClass().getResource("/imagenes/darfpunkPor.png")); 
        contraportada = new ImageIcon(getClass().getResource("/imagenes/ContraDraf1.jpg")); 
        
        lblKirby.setIcon(null); // no mostrar gif al inicio
        lblKirby1.setIcon(portada); // mostrar primero la portada
        btnBoton1.addMouseListener(new interna()); 
        
        iniciarCambioImagenes();
    }
    
    class interna extends MouseAdapter {
        
        public void mouseClicked(MouseEvent e) {
            if (lblKirby.getIcon() == null) {
                detenerCambioImagenes();
                lblKirby1.setVisible(false); // oculta portada/contraportada
                lblKirby.setIcon(imgGif); // muestra gif
                btnBoton1.setText("Detener");
            } else {
                lblKirby.setIcon(null); // quita gif
                lblKirby1.setVisible(true); // vuelve a mostrar imágenes
                btnBoton1.setText("Escuchar");
                iniciarCambioImagenes(); // reanudar cambio de imágenes
            }
        }
    }

    private void iniciarCambioImagenes() {
        activo = true;
        hiloCambioImagen = new Thread(new CambioImagenRunnable());
        hiloCambioImagen.start();
    }
    
    private void detenerCambioImagenes() {
        activo = false;
        if (hiloCambioImagen != null && hiloCambioImagen.isAlive()) {
            hiloCambioImagen.interrupt();
        }
    }
    
    class CambioImagenRunnable implements Runnable {
        
        public void run() {
            while (activo) {
                try {
                    if (mostrarPortada) {
                        lblKirby1.setIcon(portada);
                    } else {
                        lblKirby1.setIcon(contraportada);
                    }
                    mostrarPortada = !mostrarPortada; // alternar
                    Thread.sleep(3000); // cada x segundos
                } catch (InterruptedException ex) {
                    break; // si interrumpe salir
                }
            }
        }
    }

    private void reproducirSonido() {
        try {
            if (clip != null) {
                if (clip.isRunning()) {
                    clip.stop(); // si está sonando detener
                    return;
                }
            }
            URL sonidoURL = getClass().getResource("/imagenes/PruebaAudio1.wav");
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(sonidoURL);
            clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKirby1 = new javax.swing.JLabel();
        lblKirby = new javax.swing.JLabel();
        btnBoton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBoton1.setBackground(new java.awt.Color(51, 51, 51));
        btnBoton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnBoton1.setForeground(new java.awt.Color(255, 255, 255));
        btnBoton1.setText("Escuchar");
        btnBoton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DraftPunk");

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(551, 551, 551)
                .addComponent(btnBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblKirby1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblKirby, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(btnBoton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lblKirby1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lblKirby, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton1ActionPerformed
        reproducirSonido();
    }//GEN-LAST:event_btnBoton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDraf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblKirby;
    private javax.swing.JLabel lblKirby1;
    // End of variables declaration//GEN-END:variables
}
