/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ruidosperdidos;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.sound.sampled.*;
import java.io.IOException;
import java.net.URL;


public class VentanaPunk extends javax.swing.JFrame {

   private Clip clip;
    private ImageIcon imgGif;
    private ImageIcon portada;
    private ImageIcon contraportada;
    
    private Thread hiloCambioImagen;
    private boolean activo = true;
    private boolean mostrarPortada = true;
    public VentanaPunk() {
        initComponents();
         imgGif = new ImageIcon(getClass().getResource("/imagenes/gifDisco_1.gif")); 
        portada = new ImageIcon(getClass().getResource("/imagenes/darfpunkPor.png")); 
        contraportada = new ImageIcon(getClass().getResource("/imagenes/ContraDraf1.jpg")); 
        
        lblKirby.setIcon(null); // no mostrar gif al inicio
        lblKirby1.setIcon(portada); // mostrar primero la portada
        btnBoton.addMouseListener(new VentanaPunk.interna()); 
        
        iniciarCambioImagenes();
    }

    class interna extends MouseAdapter {
        
        public void mouseClicked(MouseEvent e) {
            if (lblKirby.getIcon() == null) {
                detenerCambioImagenes();
                lblKirby1.setVisible(false); // oculta portada/contraportada
                lblKirby.setIcon(imgGif); // muestra gif
                btnBoton.setText("Detener");
            } else {
                lblKirby.setIcon(null); // quita gif
                lblKirby1.setVisible(true); // vuelve a mostrar imágenes
                btnBoton.setText("Escuchar");
                iniciarCambioImagenes(); // reanudar cambio de imágenes
            }
        }
    }

    private void iniciarCambioImagenes() {
        activo = true;
        hiloCambioImagen = new Thread(new CambioImagenRunnable());
        hiloCambioImagen.start();
    }
    
    private void detenerCambioImagenes() {
        activo = false;
        if (hiloCambioImagen != null && hiloCambioImagen.isAlive()) {
            hiloCambioImagen.interrupt();
        }
    }
    
    class CambioImagenRunnable implements Runnable {
        
        public void run() {
            while (activo) {
                try {
                    if (mostrarPortada) {
                        lblKirby1.setIcon(portada);
                    } else {
                        lblKirby1.setIcon(contraportada);
                    }
                    mostrarPortada = !mostrarPortada; // alternar
                    Thread.sleep(3000); // cada x segundos
                } catch (InterruptedException ex) {
                    break; // si interrumpe salir
                }
            }
        }
    }

    private void reproducirSonido() {
        try {
            if (clip != null) {
                if (clip.isRunning()) {
                    clip.stop(); // si está sonando detener
                    return;
                }
            }
            URL sonidoURL = getClass().getResource("/imagenes/PruebaAudio1.wav");
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(sonidoURL);
            clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            e.printStackTrace();
        }

      
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKirby1 = new javax.swing.JLabel();
        btnBoton = new javax.swing.JButton();
        lblKirby = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBoton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKirby1.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(lblKirby1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 521, 409));

        btnBoton.setBackground(new java.awt.Color(51, 51, 51));
        btnBoton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnBoton.setForeground(new java.awt.Color(255, 255, 255));
        btnBoton.setText("Escuchar");
        btnBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotonActionPerformed(evt);
            }
        });
        getContentPane().add(btnBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 73, 33));

        lblKirby.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(lblKirby, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 521, 409));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DraftPunk");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 70, 30));

        btnBoton1.setBackground(new java.awt.Color(51, 51, 51));
        btnBoton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnBoton1.setForeground(new java.awt.Color(255, 255, 255));
        btnBoton1.setText("Comprar");
        btnBoton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 73, 33));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotonActionPerformed
        reproducirSonido();
    }//GEN-LAST:event_btnBotonActionPerformed

    private void btnBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton1ActionPerformed
      Compra compra = new Compra();
            compra.setVisible(true);
        this.dispose();
           
           
    }//GEN-LAST:event_btnBoton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPunk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPunk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPunk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPunk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPunk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoton;
    private javax.swing.JButton btnBoton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblKirby;
    private javax.swing.JLabel lblKirby1;
    // End of variables declaration//GEN-END:variables
}
