/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ruidosperdidos;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author BolilloCPU
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
                this.setUndecorated(true);
        initComponents();
        lblCatalogo.setText("");
        
        this.setSize(900, 600);
                this.setLocationRelativeTo(this);
        // Creamos un panel con todo el contenido
        javax.swing.JPanel panelScroll = new javax.swing.JPanel();
        panelScroll.setLayout(null);

        panelScroll.setPreferredSize(new java.awt.Dimension(800, 2500)); // altura mayor

        // Añadimos todos los componentes al panelScroll
        panelScroll.add(jLabel2);
        panelScroll.add(jLabel3);
        panelScroll.add(jLabel4);
        panelScroll.add(jLabel5);
        panelScroll.add(jLabel6);
        panelScroll.add(lblBusca);
        panelScroll.add(lblBusca);
        panelScroll.add(lblGorillaz);
        panelScroll.add(lblfondo);
        panelScroll.add(lblStrokes);
        panelScroll.add(btnSesion);
        panelScroll.add(btnRegistrar);
        panelScroll.add(lblPunk);
        panelScroll.add(jLabel13);
       panelScroll.add(jLabel19);
        panelScroll.add(lblChangos);
        panelScroll.add(jLabel16);
        panelScroll.add(jLabel17);
        panelScroll.add(jLabel18);
        
        panelScroll.add(jLabel20);
        panelScroll.add(jLabel21);
        panelScroll.add(lbldafpunk);
        
        panelScroll.add(fondoS);
        panelScroll.add(txtBusqueda);
        panelScroll.add(header);
        panelScroll.add(exitBtn);
        panelScroll.add(exitTxt);
        
        panelScroll.add(jLabel19);
        panelScroll.add(jLabel1);
        panelScroll.add(jLabel8);
        panelScroll.add(lblCNegro);
        panelScroll.add(lblFondoA);
        panelScroll.add(lblCalaca);
        panelScroll.add(jLabel7);
        
        // Agrega el panelScroll al JScrollPane
        scroll.setViewportView(panelScroll);

        // Agrega el JScrollPane al JFrame
        this.getContentPane().add(scroll, java.awt.BorderLayout.CENTER);
        
        SetImageLebel(lblCatalogo,"src/imagenes/CD.png");
        SetImageLebel(lblBusca,"src/imagenes/busqueda.png");
        SetImageLebel(lblChangos,"src/imagenes/gorillaz.png");
        SetImageLebel(lbldafpunk,"src/imagenes/darfpunkPor.png");
        SetImageLebel(lblStrokes,"src/imagenes/TheStrokes.png");
        SetImageLebel(lblfondo,"src/imagenes/urban.png");
        SetImageLebel(exitTxt, "src/imagenes/exit.png");
         ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/imagenes/fondoRpp.png"));
lblFondoA.setIcon(hacerImagenTenue(iconoOriginal, 0.5f)); // 30% visible

 ImageIcon iconoOriginal1 = new ImageIcon(getClass().getResource("/imagenes/calacach.png"));
lblCalaca.setIcon(hacerImagenTenue(iconoOriginal1, 0.5f)); // 30% visible
    }

    int xMouse, yMouse;

    public void SetImageLebel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    public ImageIcon hacerImagenTenue(ImageIcon original, float opacidad) {
    BufferedImage originalImage = new BufferedImage(
        original.getIconWidth(),
        original.getIconHeight(),
        BufferedImage.TYPE_INT_ARGB);

    Graphics2D g2d = originalImage.createGraphics();
    g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, opacidad));
    g2d.drawImage(original.getImage(), 0, 0, null);
    g2d.dispose();

    return new ImageIcon(originalImage);
}
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCatalogo = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();
        lblGorillaz = new javax.swing.JLabel();
        lblStrokes = new javax.swing.JLabel();
        lblPunk = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnSesion = new javax.swing.JButton();
        lblChangos = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbldafpunk = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblBusca = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCarrito = new javax.swing.JLabel();
        fondoS = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCNegro = new javax.swing.JLabel();
        lblFondoA = new javax.swing.JLabel();
        lblCalaca = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setOpaque(true);
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLayeredPane2.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1950");
        jLayeredPane2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 37, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1960");
        jLayeredPane2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 30, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("1970");
        jLayeredPane2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 30, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1980");
        jLayeredPane2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 30, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("1990");
        jLayeredPane2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 30, -1));

        txtBusqueda.setOpaque(true);
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        jLayeredPane2.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 180, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Catalogo");

        lblCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CD_resized_40x40.png"))); // NOI18N
        lblCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCatalogoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCatalogo)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 100, 40));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/urban.jpg"))); // NOI18N
        jLayeredPane2.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 810, 410));

        lblGorillaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorillaz.png"))); // NOI18N
        lblGorillaz.setText("jLabel9");
        lblGorillaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGorillazMouseClicked(evt);
            }
        });
        jLayeredPane2.add(lblGorillaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 410, 420));

        lblStrokes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TheStrokesPrin.png"))); // NOI18N
        lblStrokes.setText("jLabel9");
        jLayeredPane2.add(lblStrokes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 1940, 150, 140));

        lblPunk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/darfpunkPor.png"))); // NOI18N
        lblPunk.setText("jLabel9");
        lblPunk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPunkMouseClicked(evt);
            }
        });
        jLayeredPane2.add(lblPunk, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1010, 410, 410));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TheStrokes.png"))); // NOI18N
        jLabel13.setText("jLabel9");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jLayeredPane2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1430, 410, 410));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("<html>El sexto album de estudio de la aclamada banda francesa M83, Un album que nos pone en <br>posicion introspectiva sobre la vida y problemas internos de nosotros pero no importa por que al final solo estamos durmiendo.</html>");
        jLayeredPane2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 1940, 280, 130));

        btnRegistrar.setBackground(new java.awt.Color(51, 51, 51));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrarse");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 26, 100, 30));

        btnSesion.setBackground(new java.awt.Color(51, 51, 51));
        btnSesion.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnSesion.setText("Iniciar Sesión");
        btnSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesionActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 26, 120, 30));

        lblChangos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gorillazPri.png"))); // NOI18N
        lblChangos.setText("jLabel9");
        jLayeredPane2.add(lblChangos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 2110, 150, 140));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("<html>El primer disco de estudio de la agrupacion francesa daft punk con el cual cuentan con <br>artistas invitados como Julian Casablancas<br>Pharrell Williams NileRodgers Giorgo Moroder y otros.</html>");
        jLayeredPane2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1940, 260, 130));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLayeredPane2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2250, 950, 20));

        lbldafpunk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/darfpunkPrin.png"))); // NOI18N
        lbldafpunk.setText("jLabel9");
        jLayeredPane2.add(lbldafpunk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1930, 150, 140));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("<html>Visitanos<br>Ubicanos en:<br>Ruidos_Perdidos@gmail.com<br>21°28'35.2\"N 104°51'54.7\"W</html>");
        jLayeredPane2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 2260, 190, 130));
        jLayeredPane2.add(lblBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 80, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("<html>El primer disco de estudio de la agrupacion<br>francesa daft punk con el cual cuentan con <br>artistas invitados como Julian Casablancas<br>Pharrell Williams NileRodgers Giorgo Moroder y otros.</html>");
        jLayeredPane2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 2120, 290, 130));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("<html>Contacta con nosotros<br>Email: <br>Ruidos_Perdidos@gmail.com<br>Telefono<br>311-654-32-12</html>");
        jLayeredPane2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 2260, 190, 130));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(40, 40));

        lblCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito_40x40.png"))); // NOI18N
        lblCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarritoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLayeredPane2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 60, 50));

        fondoS.setBackground(new java.awt.Color(102, 102, 102));
        fondoS.setForeground(new java.awt.Color(153, 153, 153));
        fondoS.setOpaque(true);
        jLayeredPane2.add(fondoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 90));
        jLayeredPane2.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 840, 70, 140));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descripción");
        jLayeredPane2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1870, 210, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Discos de la semana");
        jLayeredPane2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, -1));

        lblCNegro.setBackground(new java.awt.Color(204, 204, 204));
        lblCNegro.setOpaque(true);
        jLayeredPane2.add(lblCNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 410, 50));
        jLayeredPane2.add(lblFondoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 950, 1360));
        jLayeredPane2.add(lblCalaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1860, 970, 540));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setOpaque(true);
        jLayeredPane2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 970, 2400));

        getContentPane().add(jLayeredPane2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void lblCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarritoMouseClicked
        Carrito c = new Carrito();
        c.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_lblCarritoMouseClicked

    private void lblGorillazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGorillazMouseClicked
      VentanaGorillas g = new VentanaGorillas(); // Instancia 
    g.setLocationRelativeTo(null); // Centrar en pantalla 
    g.setVisible(true); 
    }//GEN-LAST:event_lblGorillazMouseClicked

    private void lblPunkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPunkMouseClicked
      VentanaPunk p = new VentanaPunk(); 
    p.setLocationRelativeTo(null); 
    p.setVisible(true); 
    }//GEN-LAST:event_lblPunkMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
       VentanaStrokes s = new VentanaStrokes(); 
    s.setLocationRelativeTo(null); 
    s.setVisible(true); 
    }//GEN-LAST:event_jLabel13MouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitTxtMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSesionActionPerformed

    private void lblCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCatalogoMouseClicked
        Compra c = new Compra();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCatalogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSesion;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel fondoS;
    private javax.swing.JPanel header;
<<<<<<< HEAD
    private javax.swing.JLabel jLabel1;
=======
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
>>>>>>> f67e0735e5e3b6116a977763829fbb19262bdb53
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblCNegro;
    private javax.swing.JLabel lblCalaca;
    private javax.swing.JLabel lblCarrito;
    private javax.swing.JLabel lblCatalogo;
    private javax.swing.JLabel lblChangos;
    private javax.swing.JLabel lblFondoA;
    private javax.swing.JLabel lblGorillaz;
    private javax.swing.JLabel lblPunk;
    private javax.swing.JLabel lblStrokes;
    private javax.swing.JLabel lbldafpunk;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
