/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ruidosperdidos;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author BolilloCPU
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(900, 600);
                this.setLocationRelativeTo(this);
        // Creamos un panel con todo el contenido
        javax.swing.JPanel panelScroll = new javax.swing.JPanel();
        panelScroll.setLayout(null);

        panelScroll.setPreferredSize(new java.awt.Dimension(800, 2500)); // altura mayor

        // Añadimos todos los componentes al panelScroll
        panelScroll.add(lblGorillaz);
        panelScroll.add(lblfondo);
        panelScroll.add(lblStrokes);
        panelScroll.add(lblPunk);
        panelScroll.add(jLabel13);
       panelScroll.add(jLabel19);
        panelScroll.add(lblChangos);
        panelScroll.add(jLabel16);
        panelScroll.add(jLabel17);
        panelScroll.add(jLabel18);
        
        panelScroll.add(jLabel20);
        panelScroll.add(jLabel21);
        panelScroll.add(lbldafpunk);
        
        panelScroll.add(fondoS);
        panelScroll.add(header);
        panelScroll.add(exitBtn);
        panelScroll.add(exitTxt);
        
        panelScroll.add(jLabel19);
        panelScroll.add(jLabel1);
        panelScroll.add(btnSesion1);
        
        panelScroll.add(lblFondoA);
        panelScroll.add(lblCalaca);
        panelScroll.add(jLabel7);
        
        // Agrega el panelScroll al JScrollPane
        scroll.setViewportView(panelScroll);

        // Agrega el JScrollPane al JFrame
        this.getContentPane().add(scroll, java.awt.BorderLayout.CENTER);
        
        SetImageLebel(lblChangos,"src/imagenes/gorillaz.png");
        SetImageLebel(lbldafpunk,"src/imagenes/darfpunkPor.png");
        SetImageLebel(lblStrokes,"src/imagenes/TheStrokes.png");
        SetImageLebel(lblfondo,"src/imagenes/urban.png");
        SetImageLebel(exitTxt, "src/imagenes/exit.png");
         ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/imagenes/fondoRpp.png"));
lblFondoA.setIcon(hacerImagenTenue(iconoOriginal, 0.5f)); // 30% visible

 ImageIcon iconoOriginal1 = new ImageIcon(getClass().getResource("/imagenes/calacach.png"));
lblCalaca.setIcon(hacerImagenTenue(iconoOriginal1, 0.5f)); // 30% visible
    }

    int xMouse, yMouse;

    public void SetImageLebel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    public ImageIcon hacerImagenTenue(ImageIcon original, float opacidad) {
    BufferedImage originalImage = new BufferedImage(
        original.getIconWidth(),
        original.getIconHeight(),
        BufferedImage.TYPE_INT_ARGB);

    Graphics2D g2d = originalImage.createGraphics();
    g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, opacidad));
    g2d.drawImage(original.getImage(), 0, 0, null);
    g2d.dispose();

    return new ImageIcon(originalImage);
}
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();
        lblGorillaz = new javax.swing.JLabel();
        lblStrokes = new javax.swing.JLabel();
        lblPunk = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblChangos = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnBoton2 = new javax.swing.JButton();
        lbldafpunk = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnBoton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fondoS = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        btnSesion1 = new javax.swing.JButton();
        lblFondoA = new javax.swing.JLabel();
        lblCalaca = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBoton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(153, 153, 153));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setOpaque(true);
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLayeredPane2.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/urban.jpg"))); // NOI18N
        jLayeredPane2.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 810, 410));

        lblGorillaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gorillaz.png"))); // NOI18N
        lblGorillaz.setText("jLabel9");
        lblGorillaz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGorillazMouseClicked(evt);
            }
        });
        jLayeredPane2.add(lblGorillaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 410, 420));

        lblStrokes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TheStrokesPrin.png"))); // NOI18N
        lblStrokes.setText("jLabel9");
        jLayeredPane2.add(lblStrokes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 1940, 150, 140));

        lblPunk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/darfpunkPor.png"))); // NOI18N
        lblPunk.setText("jLabel9");
        lblPunk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPunkMouseClicked(evt);
            }
        });
        jLayeredPane2.add(lblPunk, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1010, 410, 410));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TheStrokes.png"))); // NOI18N
        jLabel13.setText("jLabel9");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jLayeredPane2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1430, 410, 410));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("<html>El sexto album de estudio de la aclamada banda francesa M83, Un album que nos pone en <br>posicion introspectiva sobre la vida y problemas internos de nosotros pero no importa por que al final solo estamos durmiendo.</html>");
        jLayeredPane2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 1940, 280, 130));

        lblChangos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gorillazPri.png"))); // NOI18N
        lblChangos.setText("jLabel9");
        jLayeredPane2.add(lblChangos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 2110, 150, 140));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("<html>El primer disco de estudio de la agrupacion francesa daft punk con el cual cuentan con <br>artistas invitados como Julian Casablancas<br>Pharrell Williams NileRodgers Giorgo Moroder y otros.</html>");
        jLayeredPane2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1940, 260, 130));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        jLayeredPane2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2250, 950, 20));

        btnBoton2.setBackground(new java.awt.Color(51, 51, 51));
        btnBoton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnBoton2.setForeground(new java.awt.Color(255, 255, 255));
        btnBoton2.setText("Comprar un disco");
        btnBoton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton2ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnBoton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 190, 40));

        lbldafpunk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/darfpunkPrin.png"))); // NOI18N
        lbldafpunk.setText("jLabel9");
        jLayeredPane2.add(lbldafpunk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1930, 150, 140));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("<html>Visitanos<br>Ubicanos en:<br>Ruidos_Perdidos@gmail.com<br>21°28'35.2\"N 104°51'54.7\"W</html>");
        jLayeredPane2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 2260, 190, 130));

        btnBoton.setBackground(new java.awt.Color(51, 51, 51));
        btnBoton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnBoton.setForeground(new java.awt.Color(255, 255, 255));
        btnBoton.setText("Discos Historicos");
        btnBoton.setActionCommand("Discos Historicos");
        btnBoton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotonActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("<html>El primer disco de estudio de la agrupacion<br>francesa daft punk con el cual cuentan con <br>artistas invitados como Julian Casablancas<br>Pharrell Williams NileRodgers Giorgo Moroder y otros.</html>");
        jLayeredPane2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 2120, 290, 130));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("<html>Contacta con nosotros<br>Email: <br>Ruidos_Perdidos@gmail.com<br>Telefono<br>311-654-32-12</html>");
        jLayeredPane2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 2260, 190, 130));

        fondoS.setBackground(new java.awt.Color(102, 102, 102));
        fondoS.setForeground(new java.awt.Color(153, 153, 153));
        fondoS.setOpaque(true);
        jLayeredPane2.add(fondoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 90));
        jLayeredPane2.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 840, 70, 140));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descripción");
        jLayeredPane2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 1870, 210, -1));

        btnSesion1.setBackground(new java.awt.Color(51, 51, 51));
        btnSesion1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        btnSesion1.setForeground(new java.awt.Color(255, 255, 255));
        btnSesion1.setText("Discos de la semana");
        btnSesion1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesion1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 506, 400, 70));
        jLayeredPane2.add(lblFondoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 950, 1360));
        jLayeredPane2.add(lblCalaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1860, 970, 540));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setOpaque(true);
        jLayeredPane2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 970, 2400));

        btnBoton1.setBackground(new java.awt.Color(51, 51, 51));
        btnBoton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnBoton1.setForeground(new java.awt.Color(255, 255, 255));
        btnBoton1.setText("Discos Historicos");
        btnBoton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoton1ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnBoton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 40));

        getContentPane().add(jLayeredPane2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGorillazMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGorillazMouseClicked
      VentanaGorillas g = new VentanaGorillas(); // Instancia 
    g.setLocationRelativeTo(null); // Centrar en pantalla 
    g.setVisible(true); 
    }//GEN-LAST:event_lblGorillazMouseClicked

    private void lblPunkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPunkMouseClicked
      VentanaPunk p = new VentanaPunk(); 
    p.setLocationRelativeTo(null); 
    p.setVisible(true); 
    }//GEN-LAST:event_lblPunkMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
       VentanaStrokes s = new VentanaStrokes(); 
    s.setLocationRelativeTo(null); 
    s.setVisible(true); 
    }//GEN-LAST:event_jLabel13MouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitTxtMouseClicked

    private void btnSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSesion1ActionPerformed

    private void btnBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotonActionPerformed
        ventana_1950 vh = new ventana_1950();
        vh.setVisible(true);
    }//GEN-LAST:event_btnBotonActionPerformed

    private void btnBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBoton1ActionPerformed

    private void btnBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoton2ActionPerformed
        // TODO add your handling code here:
        Compra c = new Compra();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBoton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoton;
    private javax.swing.JButton btnBoton1;
    private javax.swing.JButton btnBoton2;
    private javax.swing.JButton btnSesion1;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel fondoS;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel lblCalaca;
    private javax.swing.JLabel lblChangos;
    private javax.swing.JLabel lblFondoA;
    private javax.swing.JLabel lblGorillaz;
    private javax.swing.JLabel lblPunk;
    private javax.swing.JLabel lblStrokes;
    private javax.swing.JLabel lbldafpunk;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
